/**
 * Generates the live-data audit reports required before live content is
 * trusted in findings:
 *
 *   npm run audit:relevance   → docs/LIVE_RELEVANCE_AUDIT.md
 *   npm run audit:voice       → docs/LIVE_VOICE_AUDIT.md
 *   npm run audit:dedup       → docs/LIVE_DEDUP_AUDIT.md
 *
 * These emit the sampled evidence with the system's decision and reason so a
 * human can mark each row correct/incorrect. The tool never marks its own
 * homework: the "manual assessment" column is left for a person to fill,
 * except where the decision is mechanically checkable.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { and, eq } from "drizzle-orm";
import { createDb } from "@/db/client";
import { authors, mentions, processingEvents } from "@/db/schema";

const DOCS = path.join(process.cwd(), "docs");

function esc(text: string | null | undefined): string {
  if (!text) return "—";
  return text.replace(/\|/g, "\\|").replace(/\n+/g, " ").trim().slice(0, 180);
}

async function relevanceAudit() {
  const { db, close } = await createDb();
  const live = await db.select().from(mentions).where(eq(mentions.dataOrigin, "live"));
  const accepted = live.filter((m) => m.relevanceStatus === "accepted");
  const rejected = live.filter((m) => m.relevanceStatus === "rejected");

  const acceptedSample = accepted.slice(0, 50);
  const rejectedSample = rejected.slice(0, 30);

  // Model-confirmation rejections are a distinct, important class.
  const confirmationRejections: string[] = [];
  for (const m of rejected) {
    const events = await db
      .select()
      .from(processingEvents)
      .where(
        and(eq(processingEvents.mentionId, m.id), eq(processingEvents.eventType, "RELEVANCE_REJECTED")),
      );
    if (events.some((e) => (e.detail as { stage?: string } | null)?.stage === "model_confirmation")) {
      confirmationRejections.push(m.id);
    }
  }

  const lines: string[] = [];
  lines.push("# Live relevance audit");
  lines.push("");
  lines.push(
    "_Generated by `npm run audit:relevance` from live collected data. The **Assessment** column is filled in by a human reviewer; rows are not self-graded._",
  );
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- Live items collected: **${live.length}**`);
  lines.push(
    `- Accepted: **${accepted.length}** (${((accepted.length / live.length) * 100).toFixed(1)}%)`,
  );
  lines.push(
    `- Rejected: **${rejected.length}** (${((rejected.length / live.length) * 100).toFixed(1)}%)`,
  );
  lines.push(
    `  - of which rejected by model relevance confirmation (passed the keyword gate, failed substance): **${confirmationRejections.length}**`,
  );
  lines.push("");
  lines.push("## False-positive categories to watch");
  lines.push("");
  lines.push("| Code | Category |");
  lines.push("|---|---|");
  lines.push("| FP-1 | Agriculture outside Telangana (e.g. Andhra Pradesh, national) |");
  lines.push("| FP-2 | Telangana but not agriculture |");
  lines.push("| FP-3 | Political speech carrying an agriculture keyword, no substantive content |");
  lines.push("| FP-4 | Agriculture education / how-to content with no Telangana public-issue signal |");
  lines.push("| FP-5 | Generic Indian agriculture |");
  lines.push("| FP-6 | Acronym / term collision |");
  lines.push("");
  lines.push(`## Accepted sample (${acceptedSample.length})`);
  lines.push("");
  lines.push("| # | Channel | Title | District | Topics | TS | AG | Assessment |");
  lines.push("|---|---|---|---|---|---|---|---|");
  let i = 1;
  for (const m of acceptedSample) {
    const [a] = m.authorId
      ? await db.select().from(authors).where(eq(authors.id, m.authorId))
      : [null];
    lines.push(
      `| ${i++} | ${esc(a?.name)} | ${esc(m.title)} | ${m.district ?? "—"} | ${
        m.topics.join(", ") || "—"
      } | ${m.telanganaRelevance?.toFixed(2) ?? "—"} | ${m.agricultureRelevance?.toFixed(2) ?? "—"} | |`,
    );
  }
  lines.push("");
  lines.push(`## Rejected sample (${rejectedSample.length})`);
  lines.push("");
  lines.push("| # | Channel | Title | Reason | Assessment |");
  lines.push("|---|---|---|---|---|");
  i = 1;
  for (const m of rejectedSample) {
    const [a] = m.authorId
      ? await db.select().from(authors).where(eq(authors.id, m.authorId))
      : [null];
    lines.push(`| ${i++} | ${esc(a?.name)} | ${esc(m.title)} | ${esc(m.relevanceReason)} | |`);
  }
  lines.push("");
  writeFileSync(path.join(DOCS, "LIVE_RELEVANCE_AUDIT.md"), lines.join("\n"));
  console.log(
    `docs/LIVE_RELEVANCE_AUDIT.md — ${acceptedSample.length} accepted, ${rejectedSample.length} rejected sampled`,
  );
  await close();
}

async function voiceAudit() {
  const { db, close } = await createDb();
  const liveAuthors = await db.select().from(authors).where(eq(authors.dataOrigin, "live"));

  const lines: string[] = [];
  lines.push("# Live author / voice classification audit");
  lines.push("");
  lines.push(
    "_Generated by `npm run audit:voice`. Classification uses author metadata plus content; identity is never inferred beyond what public metadata states. The **Assessment** column is for a human reviewer._",
  );
  lines.push("");
  lines.push(`- Live authors: **${liveAuthors.length}**`);
  const classified = liveAuthors.filter((a) => a.authorType !== "unknown");
  lines.push(
    `- Classified (not "unknown"): **${classified.length}** (${
      liveAuthors.length ? ((classified.length / liveAuthors.length) * 100).toFixed(1) : "0"
    }%)`,
  );
  lines.push("");
  const distribution = new Map<string, number>();
  for (const a of liveAuthors) {
    distribution.set(a.authorType, (distribution.get(a.authorType) ?? 0) + 1);
  }
  lines.push("| Author type | Count |");
  lines.push("|---|---|");
  for (const [type, count] of [...distribution.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`| ${type} | ${count} |`);
  }
  lines.push("");
  lines.push("## Sample");
  lines.push("");
  lines.push("| # | Author | Platform | Classified | Conf. | Evidence used | Assessment |");
  lines.push("|---|---|---|---|---|---|---|");
  let i = 1;
  for (const a of liveAuthors.slice(0, 30)) {
    lines.push(
      `| ${i++} | ${esc(a.name)} | ${a.platform} | ${a.authorType} | ${
        a.authorTypeConfidence?.toFixed(2) ?? "—"
      } | ${esc(a.bio) } | |`,
    );
  }
  lines.push("");
  writeFileSync(path.join(DOCS, "LIVE_VOICE_AUDIT.md"), lines.join("\n"));
  console.log(`docs/LIVE_VOICE_AUDIT.md — ${Math.min(30, liveAuthors.length)} authors sampled`);
  await close();
}

async function dedupAudit() {
  const { db, close } = await createDb();
  const live = await db.select().from(mentions).where(eq(mentions.dataOrigin, "live"));
  const dupes = live.filter((m) => m.status === "duplicate");
  const accepted = live.filter((m) => m.relevanceStatus === "accepted");

  const lines: string[] = [];
  lines.push("# Live deduplication audit");
  lines.push("");
  lines.push(
    "_Generated by `npm run audit:dedup`. The governing rule is **same content ≠ same claim**: independent people reporting the same issue must remain separate voices._",
  );
  lines.push("");
  lines.push(`- Accepted live items: **${accepted.length}**`);
  lines.push(
    `- Marked duplicate: **${dupes.length}** (${
      accepted.length ? ((dupes.length / accepted.length) * 100).toFixed(1) : "0"
    }% of accepted)`,
  );
  lines.push(`  - exact: ${dupes.filter((d) => d.duplicateType === "exact").length}`);
  lines.push(`  - near: ${dupes.filter((d) => d.duplicateType === "near").length}`);
  lines.push("");
  lines.push("| Type | Sim | Duplicate | Canonical | Correct? |");
  lines.push("|---|---|---|---|---|");
  for (const d of dupes) {
    const [canon] = d.duplicateOfMentionId
      ? await db.select().from(mentions).where(eq(mentions.id, d.duplicateOfMentionId))
      : [null];
    const [event] = await db
      .select()
      .from(processingEvents)
      .where(and(eq(processingEvents.mentionId, d.id), eq(processingEvents.eventType, "DEDUPED")));
    const similarity = (event?.detail as { similarity?: number } | null)?.similarity;
    lines.push(
      `| ${d.duplicateType} | ${similarity ?? "—"} | ${esc(d.title)} | ${esc(canon?.title)} | |`,
    );
  }
  lines.push("");
  writeFileSync(path.join(DOCS, "LIVE_DEDUP_AUDIT.md"), lines.join("\n"));
  console.log(`docs/LIVE_DEDUP_AUDIT.md — ${dupes.length} duplicate pairs listed`);
  await close();
}

const mode = process.argv[2];
const run =
  mode === "relevance"
    ? relevanceAudit
    : mode === "voice"
      ? voiceAudit
      : mode === "dedup"
        ? dedupAudit
        : null;

if (!run) {
  console.error("usage: audit-report.ts <relevance|voice|dedup>");
  process.exit(1);
}
run().catch((error) => {
  console.error(error);
  process.exit(1);
});
