#!/bin/bash
#
# Install the launchd agent that keeps collection running.
#
#   ./scripts/install-scheduler.sh            install and start
#   ./scripts/install-scheduler.sh --uninstall
#
# WHY THE LAUNCHER IS WRITTEN OUTSIDE THIS REPO
#
# The project sits under ~/Desktop, which macOS protects with TCC. A launchd
# job may not read files there using Apple's platform binaries: /bin/bash and
# /usr/bin/head both get "Operation not permitted". Measured, not assumed —
# under launchd, `cd` into the project succeeds, `head scripts/<file>` is
# denied, and node reading package.json succeeds.
#
# So this script generates the launcher into ~/Library/Application Support,
# where bash may read it, and everything touching the repo is done by the nvm
# node binary, which TCC permits. Run this from Terminal, where no such
# restriction applies. Moving the project out of ~/Desktop would remove the
# whole problem, if that is ever convenient.
set -euo pipefail

LABEL="com.likhithlabs.agri-scheduler"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
SUPPORT_DIR="$HOME/Library/Application Support/agri-scheduler"
LAUNCHER="$SUPPORT_DIR/run-cycle.sh"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NODE_BIN="$(dirname "$(command -v node)")"

if [ "${1:-}" = "--uninstall" ]; then
  launchctl unload -w "$PLIST" 2>/dev/null || true
  rm -f "$PLIST" "$LAUNCHER"
  echo "Scheduler removed. Collection has stopped."
  exit 0
fi

mkdir -p "$SUPPORT_DIR" "$HOME/Library/LaunchAgents"

cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/bash
# Generated by scripts/install-scheduler.sh — edit that, not this.
set -uo pipefail
PROJECT_DIR="$PROJECT_DIR"
NODE_BIN="$NODE_BIN"
LOG="\$HOME/Library/Logs/agri-scheduler.log"

# node and the Claude CLI used for enrichment both live here.
export PATH="\$NODE_BIN:/usr/bin:/bin:/usr/sbin:/sbin"
cd "\$PROJECT_DIR" || { echo "cannot cd to project" >> "\$LOG"; exit 1; }

if [ -f "\$LOG" ] && [ "\$(wc -c < "\$LOG")" -gt 5000000 ]; then
  tail -c 1000000 "\$LOG" > "\$LOG.tmp" && mv "\$LOG.tmp" "\$LOG"
fi
echo "=== cycle starting \$(date '+%Y-%m-%d %H:%M:%S %Z') ===" >> "\$LOG"

# tsx is invoked directly rather than through \`npm run\`: npm executes package
# scripts via \`sh -c\`, and that sh would have to read node_modules inside the
# TCC-protected directory.
"\$NODE_BIN/node" "\$PROJECT_DIR/node_modules/tsx/dist/cli.mjs" \\
  --tsconfig "\$PROJECT_DIR/tsconfig.scripts.json" \\
  "\$PROJECT_DIR/scripts/scheduler.ts" --once >> "\$LOG" 2>&1 &
CYCLE_PID=\$!

# A hung cycle blocks every later one, since launchd will not start a second
# copy of a running job. Three hours is generous on purpose: a large
# enrichment backlog is slow, but it is real work rather than a hang.
( sleep 10800; kill -0 "\$CYCLE_PID" 2>/dev/null && \\
    { echo "watchdog: cycle exceeded 3h, terminating" >> "\$LOG"; kill -TERM "\$CYCLE_PID"; } ) &
WATCHDOG_PID=\$!

wait "\$CYCLE_PID"
STATUS=\$?
kill "\$WATCHDOG_PID" 2>/dev/null
echo "=== cycle finished \$(date '+%Y-%m-%d %H:%M:%S %Z') exit=\$STATUS ===" >> "\$LOG"
exit "\$STATUS"
LAUNCHER_EOF
chmod +x "$LAUNCHER"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$LAUNCHER</string>
  </array>
  <!-- One cycle an hour. Per-query cadence lives in collection_queries and is
       enforced by the router, so this only decides how often the system asks:
       news every 4h, YouTube every 6h, the paid Apify sources once a day. -->
  <key>StartInterval</key>
  <integer>3600</integer>
  <!-- Collect at login rather than waiting out the first hour. A day without
       collection is permanently missing. -->
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$HOME/Library/Logs/agri-scheduler.launchd.out.log</string>
  <key>StandardErrorPath</key>
  <string>$HOME/Library/Logs/agri-scheduler.launchd.err.log</string>
  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
PLIST_EOF

plutil -lint "$PLIST" >/dev/null
launchctl unload -w "$PLIST" 2>/dev/null || true
launchctl load -w "$PLIST"

echo "Installed $LABEL"
echo "  launcher : $LAUNCHER"
echo "  log      : ~/Library/Logs/agri-scheduler.log"
echo "  status   : launchctl list | grep agri-scheduler"
echo "  stop     : ./scripts/install-scheduler.sh --uninstall"
