#!/bin/bash
#
# Install the launchd agent that keeps collection running.
#
#   ./scripts/install-scheduler.sh            install and start
#   ./scripts/install-scheduler.sh --uninstall
#
# KEEP THIS PROJECT OUT OF ~/Desktop AND ~/Documents
#
# It used to live under ~/Desktop, and two separate things went wrong there.
# Both are fixed by the location, not by code, so they are recorded here
# rather than worked around.
#
# 1. iCloud eviction — the real one, and it cost days of collection. With
#    Desktop & Documents sync on, macOS evicts file contents to iCloud to
#    reclaim disk, leaving a full-size stub flagged `dataless` (visible via
#    `ls -lO`). A foreground process transparently downloads it again; a
#    launchd job cannot, and the read fails with EAGAIN, surfacing as
#    "Unknown system error -11" mid-import. So cycles died at random, in
#    whichever dependency happened to be evicted that hour, and a `mv` out of
#    the folder blocks indefinitely on the first file that will not come back
#    down. Delete node_modules before moving; npm ci rebuilds it.
#
# 2. TCC — the theory this comment used to give, and only half right. Under
#    launchd, `cd` into a Desktop project succeeds and `head scripts/<file>`
#    is denied, so Apple's platform binaries genuinely are restricted there.
#    That is why the launcher is still generated into ~/Library/Application
#    Support and everything touching the repo goes through the nvm node
#    binary. Harmless to keep, and it costs nothing outside ~/Desktop.
#
# PROJECT_DIR below is baked into the generated launcher, so re-run this
# script after moving the project or launchd keeps using the old path.
set -euo pipefail

LABEL="com.likhithlabs.agri-scheduler"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
SUPPORT_DIR="$HOME/Library/Application Support/agri-scheduler"
LAUNCHER="$SUPPORT_DIR/run-cycle.sh"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NODE_BIN="$(dirname "$(command -v node)")"

if [ "${1:-}" = "--uninstall" ]; then
  launchctl unload -w "$PLIST" 2>/dev/null || true
  rm -f "$PLIST" "$LAUNCHER"
  echo "Scheduler removed. Collection has stopped."
  exit 0
fi

mkdir -p "$SUPPORT_DIR" "$HOME/Library/LaunchAgents"

cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/bash
# Generated by scripts/install-scheduler.sh — edit that, not this.
set -uo pipefail
PROJECT_DIR="$PROJECT_DIR"
NODE_BIN="$NODE_BIN"
LOG="\$HOME/Library/Logs/agri-scheduler.log"

# node and the Claude CLI used for enrichment both live here.
export PATH="\$NODE_BIN:/usr/bin:/bin:/usr/sbin:/sbin"
cd "\$PROJECT_DIR" || { echo "cannot cd to project" >> "\$LOG"; exit 1; }

if [ -f "\$LOG" ] && [ "\$(wc -c < "\$LOG")" -gt 5000000 ]; then
  tail -c 1000000 "\$LOG" > "\$LOG.tmp" && mv "\$LOG.tmp" "\$LOG"
fi
echo "=== cycle starting \$(date '+%Y-%m-%d %H:%M:%S %Z') ===" >> "\$LOG"

# tsx is invoked directly rather than through \`npm run\`: npm executes package
# scripts via \`sh -c\`, and that sh would have to read node_modules inside the
# TCC-protected directory.
"\$NODE_BIN/node" "\$PROJECT_DIR/node_modules/tsx/dist/cli.mjs" \\
  --tsconfig "\$PROJECT_DIR/tsconfig.scripts.json" \\
  "\$PROJECT_DIR/scripts/scheduler.ts" --once >> "\$LOG" 2>&1 &
CYCLE_PID=\$!

# A hung cycle blocks every later one, since launchd will not start a second
# copy of a running job. Three hours is generous on purpose: a large
# enrichment backlog is slow, but it is real work rather than a hang.
( sleep 10800; kill -0 "\$CYCLE_PID" 2>/dev/null && \\
    { echo "watchdog: cycle exceeded 3h, terminating" >> "\$LOG"; kill -TERM "\$CYCLE_PID"; } ) &
WATCHDOG_PID=\$!

wait "\$CYCLE_PID"
STATUS=\$?
kill "\$WATCHDOG_PID" 2>/dev/null
echo "=== cycle finished \$(date '+%Y-%m-%d %H:%M:%S %Z') exit=\$STATUS ===" >> "\$LOG"
exit "\$STATUS"
LAUNCHER_EOF
chmod +x "$LAUNCHER"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$LAUNCHER</string>
  </array>
  <!-- One cycle every 30 minutes, matching SCAN_MINUTES in
       src/ontology/queries.ts. Both levers must agree: per-query cadence lives
       in collection_queries and is enforced by the router, so a 30-minute
       cadence with an hourly tick still only scans hourly, and an hourly
       cadence with a 30-minute tick just adds an idle cycle. A cycle takes
       9-23 minutes, so this leaves real but not generous headroom; launchd
       will not start a second copy while one is running, and an overrun
       simply skips a tick. -->
  <key>StartInterval</key>
  <integer>1800</integer>
  <!-- Collect at login rather than waiting out the first hour. A day without
       collection is permanently missing. -->
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$HOME/Library/Logs/agri-scheduler.launchd.out.log</string>
  <key>StandardErrorPath</key>
  <string>$HOME/Library/Logs/agri-scheduler.launchd.err.log</string>
  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
PLIST_EOF

plutil -lint "$PLIST" >/dev/null
launchctl unload -w "$PLIST" 2>/dev/null || true
launchctl load -w "$PLIST"

echo "Installed $LABEL"
echo "  launcher : $LAUNCHER"
echo "  log      : ~/Library/Logs/agri-scheduler.log"
echo "  status   : launchctl list | grep agri-scheduler"
echo "  stop     : ./scripts/install-scheduler.sh --uninstall"
